[package]
name = "advancedresearch-lojban"
version = "0.1.0"
authors = ["Sven Nilsen <bvssvni@gmail.com>"]

[lib]
name = "lojban"

[[bin]]
name = "corpus"
path = "src/bin/corpus.rs"

[dependencies]
piston_meta = "1.0.0"
